-- Crilo: add 19 more memorable-number badges.
-- Scores 5 and 7 were deployed separately.
-- Preserves existing awards, wheel badges, and score rarity badges.
insert into public.badges (badge_key,name,description,category,requirement,is_secret,sort_order) values
('v2_funny_score_10','Perfect Ten','Reach exactly 10 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":10,"rarity":"uncommon","probability_percent":24.13185,"simulation_runs":2000000}'::jsonb,false,232),
('v2_funny_score_11','Make a Wish','Reach exactly 11 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":11,"rarity":"uncommon","probability_percent":18.41335,"simulation_runs":2000000}'::jsonb,false,233),
('v2_funny_score_12','A Dozen','Reach exactly 12 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":12,"rarity":"uncommon","probability_percent":21.10005,"simulation_runs":2000000}'::jsonb,false,234),
('v2_funny_score_13','Unlucky Thirteen','Reach exactly 13 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":13,"rarity":"uncommon","probability_percent":13.9065,"simulation_runs":2000000}'::jsonb,false,235),
('v2_funny_score_15','Quarter Hour','Reach exactly 15 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":15,"rarity":"uncommon","probability_percent":14.17565,"simulation_runs":2000000}'::jsonb,false,236),
('v2_funny_score_20','Twenty Twenty','Reach exactly 20 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":20,"rarity":"rare","probability_percent":7.842,"simulation_runs":2000000}'::jsonb,false,237),
('v2_funny_score_24','Around the Clock','Reach exactly 24 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":24,"rarity":"rare","probability_percent":8.37995,"simulation_runs":2000000}'::jsonb,false,238),
('v2_funny_score_25','Quarter Century','Reach exactly 25 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":25,"rarity":"epic","probability_percent":4.3397,"simulation_runs":2000000}'::jsonb,false,239),
('v2_funny_score_30','Thirty Flirty','Reach exactly 30 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":30,"rarity":"rare","probability_percent":6.42925,"simulation_runs":2000000}'::jsonb,false,240),
('v2_funny_score_33','Double Threes','Reach exactly 33 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":33,"rarity":"epic","probability_percent":4.91135,"simulation_runs":2000000}'::jsonb,false,241),
('v2_funny_score_50','Half a Century','Reach exactly 50 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":50,"rarity":"anomaly","probability_percent":1.35295,"simulation_runs":2000000}'::jsonb,false,242),
('v2_funny_score_55','Double Fives','Reach exactly 55 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":55,"rarity":"mythic","probability_percent":0.9304,"simulation_runs":2000000}'::jsonb,false,243),
('v2_funny_score_66','Double Sixes','Reach exactly 66 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":66,"rarity":"anomaly","probability_percent":1.4648,"simulation_runs":2000000}'::jsonb,false,244),
('v2_funny_score_70','Seventy Up','Reach exactly 70 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":70,"rarity":"mythic","probability_percent":0.54065,"simulation_runs":2000000}'::jsonb,false,245),
('v2_funny_score_77','Double Lucky','Reach exactly 77 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":77,"rarity":"mythic","probability_percent":0.37315,"simulation_runs":2000000}'::jsonb,false,246),
('v2_funny_score_88','Double Eights','Reach exactly 88 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":88,"rarity":"mythic","probability_percent":0.31605,"simulation_runs":2000000}'::jsonb,false,247),
('v2_funny_score_100','Triple Digits','Reach exactly 100 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":100,"rarity":"mythic","probability_percent":0.27865,"simulation_runs":2000000}'::jsonb,false,248),
('v2_funny_score_101','Introduction to Numbers','Reach exactly 101 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":101,"rarity":"mythic","probability_percent":0.22015,"simulation_runs":2000000}'::jsonb,false,249),
('v2_funny_score_200','Double Century','Reach exactly 200 points at least once during an official Daily run (not necessarily your final score).','funny_score','{"type":"score_reached","score":200,"rarity":"mythic","probability_percent":0.04405,"simulation_runs":2000000}'::jsonb,false,250)
on conflict (badge_key) do update set name=excluded.name,description=excluded.description,requirement=excluded.requirement;

-- All funny-score descriptions explicitly say the number may occur mid-run.
update public.badges set description='Reach exactly '||(requirement->>'score')||' points at least once during an official Daily run (not necessarily your final score).'
where category='funny_score';
