-- Crilo friends backend for the existing friends.html/friends.js.
-- Run once in Supabase SQL Editor. Requires public.profiles and public.badges.
CREATE TABLE IF NOT EXISTS public.friend_requests (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 sender_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 receiver_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','declined')),
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT crilo_no_self_friend CHECK(sender_id<>receiver_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS crilo_one_friend_pair
 ON public.friend_requests (LEAST(sender_id,receiver_id),GREATEST(sender_id,receiver_id));
CREATE INDEX IF NOT EXISTS crilo_friend_sender ON public.friend_requests(sender_id,status);
CREATE INDEX IF NOT EXISTS crilo_friend_receiver ON public.friend_requests(receiver_id,status);
ALTER TABLE public.friend_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS crilo_friend_participant_read ON public.friend_requests;
CREATE POLICY crilo_friend_participant_read ON public.friend_requests
 FOR SELECT TO authenticated USING(auth.uid()=sender_id OR auth.uid()=receiver_id);
REVOKE ALL ON public.friend_requests FROM anon,authenticated;
GRANT SELECT ON public.friend_requests TO authenticated;

CREATE OR REPLACE FUNCTION public.search_crilo_players(search_text text)
RETURNS TABLE(id uuid,username text,name_color text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE q text:=left(trim(coalesce(search_text,'')),80);
BEGIN
 IF auth.uid() IS NULL OR length(q)<2 THEN RETURN;END IF;
 RETURN QUERY
 SELECT p.id,p.username::text,p.name_color::text
 FROM public.profiles p
 WHERE p.id<>auth.uid()
 AND (p.username ILIKE '%'||replace(replace(replace(q,'\\','\\\\'),'%','\\%'),'_','\\_')||'%' ESCAPE '\'
      OR upper(p.account_code::text)=upper(q))
 ORDER BY CASE WHEN lower(p.username)=lower(q) THEN 0 ELSE 1 END,p.username
 LIMIT 20;
END $$;

CREATE OR REPLACE FUNCTION public.send_friend_request(target_user uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE me uuid:=auth.uid();r public.friend_requests%rowtype;
BEGIN
 IF me IS NULL THEN RAISE EXCEPTION 'Sign in required';END IF;
 IF target_user IS NULL OR target_user=me THEN RAISE EXCEPTION 'Invalid friend';END IF;
 IF NOT EXISTS(SELECT 1 FROM public.profiles WHERE id=target_user) THEN RAISE EXCEPTION 'Player not found';END IF;
 SELECT * INTO r FROM public.friend_requests
 WHERE (sender_id=me AND receiver_id=target_user) OR (sender_id=target_user AND receiver_id=me)
 FOR UPDATE;
 IF FOUND THEN
  IF r.status='accepted' THEN RETURN;END IF;
  IF r.status='pending' THEN
   IF r.receiver_id=me THEN
    UPDATE public.friend_requests SET status='accepted',updated_at=now() WHERE id=r.id;
   END IF;
   RETURN;
  END IF;
  UPDATE public.friend_requests SET sender_id=me,receiver_id=target_user,status='pending',updated_at=now() WHERE id=r.id;
 ELSE
  INSERT INTO public.friend_requests(sender_id,receiver_id) VALUES(me,target_user);
 END IF;
END $$;

CREATE OR REPLACE FUNCTION public.accept_friend_request(request_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 UPDATE public.friend_requests SET status='accepted',updated_at=now()
 WHERE id=request_id AND receiver_id=auth.uid() AND status='pending';
 IF NOT FOUND THEN RAISE EXCEPTION 'Pending incoming request not found';END IF;
END $$;

CREATE OR REPLACE FUNCTION public.decline_friend_request(request_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 UPDATE public.friend_requests SET status='declined',updated_at=now()
 WHERE id=request_id AND receiver_id=auth.uid() AND status='pending';
 IF NOT FOUND THEN RAISE EXCEPTION 'Pending incoming request not found';END IF;
END $$;

CREATE OR REPLACE FUNCTION public.remove_crilo_friend(friend_user uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 DELETE FROM public.friend_requests WHERE status='accepted'
 AND ((sender_id=auth.uid() AND receiver_id=friend_user)
 OR (receiver_id=auth.uid() AND sender_id=friend_user));
 IF NOT FOUND THEN RAISE EXCEPTION 'Friendship not found';END IF;
END $$;

CREATE OR REPLACE FUNCTION public.crilo_award_friend_badges(p_user uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE friend_count bigint;
BEGIN
 SELECT count(*) INTO friend_count FROM public.friend_requests
 WHERE status='accepted' AND (sender_id=p_user OR receiver_id=p_user);
 INSERT INTO public.user_badges(user_id,badge_id,earned_at)
 SELECT p_user,b.id,now() FROM public.badges b
 WHERE (b.badge_key='social_friend1' AND friend_count>=1)
 OR (b.badge_key='social_friend5' AND friend_count>=5)
 OR (b.badge_key='social_friend25' AND friend_count>=25)
 ON CONFLICT DO NOTHING;
END $$;
CREATE OR REPLACE FUNCTION public.crilo_friend_badge_trigger()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF NEW.status='accepted' AND (TG_OP='INSERT' OR OLD.status IS DISTINCT FROM 'accepted') THEN
  PERFORM public.crilo_award_friend_badges(NEW.sender_id);
  PERFORM public.crilo_award_friend_badges(NEW.receiver_id);
 END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS crilo_friend_badges_on_accept ON public.friend_requests;
CREATE TRIGGER crilo_friend_badges_on_accept
AFTER INSERT OR UPDATE ON public.friend_requests
FOR EACH ROW EXECUTE FUNCTION public.crilo_friend_badge_trigger();

REVOKE ALL ON FUNCTION public.search_crilo_players(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.send_friend_request(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.accept_friend_request(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.decline_friend_request(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.remove_crilo_friend(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.crilo_award_friend_badges(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.crilo_friend_badge_trigger() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.search_crilo_players(text),
 public.send_friend_request(uuid),public.accept_friend_request(bigint),
 public.decline_friend_request(bigint),public.remove_crilo_friend(uuid) TO authenticated;

SELECT b.badge_key,b.name,b.description FROM public.badges b
WHERE b.badge_key IN ('social_friend1','social_friend5','social_friend25') ORDER BY b.badge_key;
